clean:
	@echo "---------------------------------"
	@echo " REMOVING ALL AUTO COMPILED STUFF"
	@echo "---------------------------------"
	rm *.pyc; rm -r __pycache__;rm *.o;rm main.exe;rm .sconsign.dblite; rm *.pyd;rm -r build;rm samir.c;
